# Create a 1D NumPy array containing the integers from 0 to 9.

In [2]:
import numpy as np
array_1d = np.arange(10)
print("1D NumPy array:", array_1d)

1D NumPy array: [0 1 2 3 4 5 6 7 8 9]


In [3]:
array_1d = np.array([i for i in range(10)])
print("1D NumPy array:", array_1d)

1D NumPy array: [0 1 2 3 4 5 6 7 8 9]


In [4]:
array_1d = np.linspace(0, 9, 10, dtype=int)
print("1D NumPy array:", array_1d)

1D NumPy array: [0 1 2 3 4 5 6 7 8 9]


In [5]:
array_1d = np.array(list(range(10)))
print("1D NumPy array:", array_1d)

1D NumPy array: [0 1 2 3 4 5 6 7 8 9]


In [6]:
array_1d = np.zeros(10, dtype=int)
array_1d[:] = np.arange(10)
print("1D NumPy array:", array_1d)

1D NumPy array: [0 1 2 3 4 5 6 7 8 9]


# Create a 2D NumPy array (3x3) containing random integers between 1 and 20.


In [8]:
array_2d_1 = np.random.randint(1, 21, size=(3, 3))
print(array_2d_1)

[[13 11  8]
 [14  8  3]
 [10 11 16]]


In [9]:
array_2d_2 = np.round(np.random.random((3, 3)) * 20)
print(array_2d_2)

[[16. 10. 14.]
 [ 5. 11. 13.]
 [14. 17. 17.]]


In [10]:
choices = np.arange(1, 21)
array_2d_3 = np.random.choice(choices, size=(3, 3))
print(array_2d_3)

[[ 2  5 17]
 [ 4 19  3]
 [10  8 17]]


In [11]:
array_2d_4 = np.round(np.random.uniform(1, 21, size=(3, 3)))
print(array_2d_4)


[[12.  5.  7.]
 [ 4. 20. 16.]
 [10. 14.  3.]]


In [12]:
mean = 10.5  # Mean value around which to generate numbers
std_dev = 5  # Standard deviation
array_2d_5 = np.random.normal(mean, std_dev, size=(3, 3)).astype(int)
array_2d_5 = np.clip(array_2d_5, 1, 20)  # Clip values to be within range [1, 20]
print(array_2d_5)


[[ 1  6 15]
 [16  8  6]
 [ 7  9  3]]


# Create a 3D NumPy array with dimensions (2, 3, 4) filled with ones.


In [13]:
array_3d = np.ones((2, 3, 4))

print("3D NumPy array:")
print(array_3d)


3D NumPy array:
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [14]:
array_3d = np.full((2, 3, 4), 1)

print("3D NumPy array:")
print(array_3d)


3D NumPy array:
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [16]:
array_3d = np.ones((2, 3, 4), dtype=int)

print("3D NumPy array:")
print(array_3d)

3D NumPy array:
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [17]:
empty_array = np.empty((2, 3, 4))

array_3d = np.ones_like(empty_array)

print("3D NumPy array:")
print(array_3d)


3D NumPy array:
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [18]:
array_3d = np.array([[[1] * 4] * 3] * 2)

print("3D NumPy array:")
print(array_3d)


3D NumPy array:
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


# Add two 1D arrays element-wise.

In [20]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

result_method1 = array1 + array2

print("Method 1 Result:", result_method1)


Method 1 Result: [ 7  9 11 13 15]


In [21]:
result_method2 = np.add(array1, array2)

print("Method 2 Result:", result_method2)


Method 2 Result: [ 7  9 11 13 15]


In [22]:
result_method3 = np.sum([array1, array2], axis=0)

print("Method 3 Result:", result_method3)


Method 3 Result: [ 7  9 11 13 15]


In [23]:
result_method4 = np.apply_along_axis(lambda x: x[0] + x[1], axis=0, arr=np.stack((array1, array2)))

print("Method 4 Result:", result_method4)


Method 4 Result: [ 7  9 11 13 15]


In [24]:
result_method5 = np.array([x + y for x, y in zip(array1, array2)])

print("Method 5 Result:", result_method5)


Method 5 Result: [ 7  9 11 13 15]


# Multiply two 2D arrays element-wise.


In [25]:
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

result_method1 = array1 * array2

print("Method 1 Result:")
print(result_method1)


Method 1 Result:
[[ 7 16 27]
 [40 55 72]]


In [26]:
result_method2 = np.multiply(array1, array2)

print("\nMethod 2 Result:")
print(result_method2)



Method 2 Result:
[[ 7 16 27]
 [40 55 72]]


In [32]:
broadcasted_array2 = np.broadcast_to(array2, array1.shape)
result_method3 = array1 * broadcasted_array2

print("\nMethod 3 Result:")
print(result_method3)



Method 3 Result:
[[ 7 16 27]
 [40 55 72]]


In [31]:
multiply_elements = np.vectorize(lambda x, y: x * y)
result_method4 = multiply_elements(array1, array2)

print("\nMethod 4 Result:")
print(result_method4)



Method 4 Result:
[[ 7 16 27]
 [40 55 72]]


In [30]:
result_method5 = np.array([[array1[i, j] * array2[i, j] for j in range(array1.shape[1])] for i in range(array1.shape[0])])

print("\nMethod 5 Result:")
print(result_method5)



Method 5 Result:
[[ 7 16 27]
 [40 55 72]]


# Calculate the dot product of two matrices.

In [33]:
# Define two matrices
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

matrix2 = np.array([[7, 8],
                    [9, 10],
                    [11, 12]])

result_method1 = np.dot(matrix1, matrix2)

print("Method 1 Result:")
print(result_method1)


Method 1 Result:
[[ 58  64]
 [139 154]]


In [34]:
result_method2 = matrix1 @ matrix2

print("\nMethod 2 Result:")
print(result_method2)



Method 2 Result:
[[ 58  64]
 [139 154]]


In [35]:
result_method3 = np.matmul(matrix1, matrix2)

print("\nMethod 3 Result:")
print(result_method3)



Method 3 Result:
[[ 58  64]
 [139 154]]


In [36]:
result_method4 = matrix1.dot(matrix2)

print("\nMethod 4 Result:")
print(result_method4)



Method 4 Result:
[[ 58  64]
 [139 154]]


In [37]:
result_method5 = np.array([[np.sum(matrix1[row] * matrix2[:, col]) for col in range(matrix2.shape[1])] for row in range(matrix1.shape[0])])

print("\nMethod 5 Result:")
print(result_method5)



Method 5 Result:
[[ 58  64]
 [139 154]]


# Calculate the mean, median, and standard deviation of a 1D array.


In [38]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Calculate mean, median, and standard deviation using NumPy functions
mean_method1 = np.mean(arr)
median_method1 = np.median(arr)
std_method1 = np.std(arr)

print("Method 1 Results:")
print("Mean:", mean_method1)
print("Median:", median_method1)
print("Standard Deviation:", std_method1)


Method 1 Results:
Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143


In [39]:
mean_method2 = arr.mean()
median_method2 = np.median(arr)
std_method2 = np.std(arr)

print("\nMethod 2 Results:")
print("Mean:", mean_method2)
print("Median:", median_method2)
print("Standard Deviation:", std_method2)



Method 2 Results:
Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143


In [40]:
import pandas as pd

series = pd.Series(arr)
stats = series.describe()
mean_method3 = stats['mean']
median_method3 = stats['50%']  # 50% corresponds to median
std_method3 = stats['std']

print("\nMethod 3 Results:")
print("Mean:", mean_method3)
print("Median:", median_method3)
print("Standard Deviation:", std_method3)



Method 3 Results:
Mean: 5.5
Median: 5.5
Standard Deviation: 3.0276503540974917


In [41]:
mean_method4 = sum(arr) / len(arr)
sorted_arr = np.sort(arr)
n = len(sorted_arr)
median_method4 = (sorted_arr[(n - 1) // 2] + sorted_arr[n // 2]) / 2 if n % 2 == 0 else sorted_arr[n // 2]
std_method4 = np.sqrt(np.sum((arr - mean_method4)**2) / len(arr))

print("\nMethod 4 Results:")
print("Mean:", mean_method4)
print("Median:", median_method4)
print("Standard Deviation:", std_method4)



Method 4 Results:
Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143


In [45]:
from scipy import stats

# Define a 1D NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Calculate mean, median, and standard deviation using scipy.stats and np.median()
stats_result = stats.describe(arr)
mean_method5 = stats_result.mean
median_method5 = np.median(arr)
std_method5 = np.sqrt(stats_result.variance)  # Calculate standard deviation using variance

print("Method 5 Results:")
print("Mean:", mean_method5)
print("Median:", median_method5)
print("Standard Deviation:", std_method5)


Method 5 Results:
Mean: 5.5
Median: 5.5
Standard Deviation: 3.0276503540974917


# Find the maximum and minimum values in a 2D array.


In [46]:
# Define a 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Find maximum and minimum values using np.max() and np.min()
max_method1 = np.max(arr_2d)
min_method1 = np.min(arr_2d)

print("Method 1 Results:")
print("Maximum value:", max_method1)
print("Minimum value:", min_method1)


Method 1 Results:
Maximum value: 9
Minimum value: 1


In [47]:
max_method2 = arr_2d.max()
min_method2 = arr_2d.min()

print("\nMethod 2 Results:")
print("Maximum value:", max_method2)
print("Minimum value:", min_method2)



Method 2 Results:
Maximum value: 9
Minimum value: 1


In [48]:
max_method3 = np.amax(arr_2d)
min_method3 = np.amin(arr_2d)

print("\nMethod 3 Results:")
print("Maximum value:", max_method3)
print("Minimum value:", min_method3)



Method 3 Results:
Maximum value: 9
Minimum value: 1


In [49]:
# Flatten the 2D array and then find max and min
flattened_arr = arr_2d.flatten()
max_method4 = np.max(flattened_arr)
min_method4 = np.min(flattened_arr)

print("\nMethod 4 Results:")
print("Maximum value:", max_method4)
print("Minimum value:", min_method4)



Method 4 Results:
Maximum value: 9
Minimum value: 1


In [50]:
# Example with NaN values
arr_nan = np.array([[1, 2, np.nan],
                    [4, 5, 6],
                    [7, 8, 9]])

max_method5 = np.nanmax(arr_nan)
min_method5 = np.nanmin(arr_nan)

print("\nMethod 5 Results:")
print("Maximum value (ignoring NaN):", max_method5)
print("Minimum value (ignoring NaN):", min_method5)



Method 5 Results:
Maximum value (ignoring NaN): 9.0
Minimum value (ignoring NaN): 1.0


# Generate an array of 1000 random numbers from a normal distribution with a mean of 0 and a standard deviation of 1.


In [52]:
arr_method1 = np.random.normal(loc=0, scale=1, size=1000)

print("Method 1 Results:")
print(arr_method1[:10])  # Print first 10 elements for demonstration


Method 1 Results:
[ 2.58955966  0.47547622  0.17781396  0.50197016  0.05376488 -1.12097415
 -0.97004888 -0.63899793  0.7456651   0.30779211]


In [53]:
arr_method2 = np.random.randn(1000)

print("\nMethod 2 Results:")
print(arr_method2[:10])  # Print first 10 elements for demonstration



Method 2 Results:
[-0.29402489 -0.77877899 -0.28483827  0.29421969  1.13480893  2.43712645
  0.5216402   1.21088279 -0.97117873  1.14977456]


In [54]:
arr_method3 = np.random.standard_normal(1000)

print("\nMethod 3 Results:")
print(arr_method3[:10])  # Print first 10 elements for demonstration



Method 3 Results:
[ 0.18037078 -1.78024513  0.19682043  1.63008897 -0.81083985  0.42855585
 -0.27715944  0.86052716  0.83613785  2.3633256 ]


In [55]:
arr_method3 = np.random.standard_normal(1000)

print("\nMethod 3 Results:")
print(arr_method3[:10])  # Print first 10 elements for demonstration



Method 3 Results:
[-0.36551806 -0.28401556  0.42297582 -0.33966437 -0.98775447  0.09610117
 -1.47671554  0.80058382  1.05567561 -0.05694731]


# Create a 2D array of shapes (5, 5) with random integers from a uniform distribution between 10 and 50.


In [57]:
# Generate a 2D array of shape (5, 5) with random integers
arr_method1 = np.random.randint(10, 51, size=(5, 5))

print("Method 1 Results:")
print(arr_method1)


Method 1 Results:
[[42 44 48 17 33]
 [19 38 46 19 25]
 [38 41 14 20 19]
 [49 24 22 43 19]
 [23 41 38 31 17]]


In [58]:
arr_method2 = np.round(np.random.uniform(10, 50, size=(5, 5)))

print("\nMethod 2 Results:")
print(arr_method2)



Method 2 Results:
[[40. 13. 40. 26. 14.]
 [24. 13. 33. 46. 35.]
 [27. 29. 11. 12. 47.]
 [50. 39. 50. 50. 24.]
 [47. 33. 46. 22. 37.]]


In [59]:
arr_method3 = np.random.random(size=(5, 5)) * 40 + 10
arr_method3 = arr_method3.astype(int)  # Convert to integers

print("\nMethod 3 Results:")
print(arr_method3)



Method 3 Results:
[[43 13 36 29 32]
 [33 23 28 24 48]
 [30 35 21 45 47]
 [46 12 31 25 29]
 [39 43 41 28 33]]


In [60]:
rng = np.random.default_rng()
arr_method4 = rng.integers(10, 51, size=(5, 5))

print("\nMethod 4 Results:")
print(arr_method4)



Method 4 Results:
[[47 20 39 49 48]
 [39 37 50 13 21]
 [10 10 44 16 29]
 [20 21 39 44 45]
 [20 25 11 30 47]]


In [61]:
import random

arr_method5 = np.array([[random.randint(10, 50) for _ in range(5)] for _ in range(5)])

print("\nMethod 5 Results:")
print(arr_method5)



Method 5 Results:
[[42 50 10 33 18]
 [22 24 18 20 39]
 [31 18 18 19 31]
 [32 42 15 44 37]
 [33 30 38 40 24]]


# Calculate the cumulative sum of a 1D array.

In [62]:
arr = np.array([1, 2, 3, 4, 5])

# Calculate cumulative sum using np.cumsum()
cumsum_method1 = np.cumsum(arr)

print("Method 1 Results:")
print(cumsum_method1)


Method 1 Results:
[ 1  3  6 10 15]


In [63]:
cumsum_method2 = np.zeros_like(arr)
cumsum_method2[0] = arr[0]
for i in range(1, len(arr)):
    cumsum_method2[i] = cumsum_method2[i - 1] + arr[i]

print("\nMethod 2 Results:")
print(cumsum_method2)



Method 2 Results:
[ 1  3  6 10 15]


In [64]:
cumsum_method3 = np.array([sum(arr[:i+1]) for i in range(len(arr))])

print("\nMethod 3 Results:")
print(cumsum_method3)



Method 3 Results:
[ 1  3  6 10 15]


In [65]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
cumsum_method4 = np.add.accumulate(arr)

print("\nMethod  4 Results:")



Method  4 Results:


# Compute the correlation coefficient matrix of a 2D array.


In [67]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Calculate correlation coefficient matrix using np.corrcoef()
corr_matrix_method1 = np.corrcoef(arr, rowvar=False)

print("Method 1 Results:")
print(corr_matrix_method1)


Method 1 Results:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [68]:
corr_matrix_method2 = np.corrcoef(arr.T)

print("\nMethod 2 Results:")
print(corr_matrix_method2)



Method 2 Results:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [69]:
import pandas as pd

df = pd.DataFrame(arr)
corr_matrix_method3 = df.corr().values

print("\nMethod 3 Results:")
print(corr_matrix_method3)



Method 3 Results:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [70]:
from scipy.stats import pearsonr

n_cols = arr.shape[1]
corr_matrix_method4 = np.zeros((n_cols, n_cols))

for i in range(n_cols):
    for j in range(n_cols):
        corr_matrix_method4[i, j], _ = pearsonr(arr[:, i], arr[:, j])

print("\nMethod 4 Results:")
print(corr_matrix_method4)



Method 4 Results:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [73]:
corr_matrix_method5 = np.corrcoef(arr, rowvar=False)

print("Method 5 Results:")
print(corr_matrix_method5)

Method 5 Results:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# Simulate rolling a six-sided die 1000 times and count the frequency of each outcome.


In [74]:
# Simulate rolling a six-sided die 1000 times
rolls_method1 = np.random.randint(1, 7, size=1000)

# Count the frequency of each outcome using np.bincount()
freq_method1 = np.bincount(rolls_method1)[1:]

print("Method 1 Results:")
for i, freq in enumerate(freq_method1, start=1):
    print(f"Outcome {i}: {freq}")


Method 1 Results:
Outcome 1: 162
Outcome 2: 179
Outcome 3: 171
Outcome 4: 161
Outcome 5: 162
Outcome 6: 165


In [75]:
import random
from collections import Counter

# Simulate rolling a six-sided die 1000 times
rolls_method2 = [random.randint(1, 6) for _ in range(1000)]

# Count the frequency of each outcome using Counter
freq_method2 = Counter(rolls_method2)

print("\nMethod 2 Results:")
for i in range(1, 7):
    print(f"Outcome {i}: {freq_method2.get(i, 0)}")



Method 2 Results:
Outcome 1: 188
Outcome 2: 172
Outcome 3: 174
Outcome 4: 121
Outcome 5: 184
Outcome 6: 161


In [76]:
# Simulate rolling a six-sided die 1000 times
rolls_method3 = np.random.choice(np.arange(1, 7), size=1000)

# Count the frequency of each outcome using np.unique()
outcomes, freq_method3 = np.unique(rolls_method3, return_counts=True)

print("\nMethod 3 Results:")
for i, freq in zip(outcomes, freq_method3):
    print(f"Outcome {i}: {freq}")



Method 3 Results:
Outcome 1: 157
Outcome 2: 156
Outcome 3: 188
Outcome 4: 171
Outcome 5: 167
Outcome 6: 161


In [77]:
# Simulate rolling a six-sided die 1000 times
rolls_method4 = np.random.multinomial(1000, [1/6]*6)

print("\nMethod 4 Results:")
for i, freq in enumerate(rolls_method4, start=1):
    print(f"Outcome {i}: {freq}")



Method 4 Results:
Outcome 1: 161
Outcome 2: 197
Outcome 3: 135
Outcome 4: 179
Outcome 5: 166
Outcome 6: 162


In [78]:
import pandas as pd

# Simulate rolling a six-sided die 1000 times
rolls_method5 = np.random.randint(1, 7, size=1000)

# Create a Pandas DataFrame and use value_counts()
df_method5 = pd.DataFrame(rolls_method5, columns=['Outcome'])
freq_method5 = df_method5['Outcome'].value_counts().sort_index()

print("\nMethod 5 Results:")
for i, freq in freq_method5.items():
    print(f"Outcome {i}: {freq}")



Method 5 Results:
Outcome 1: 177
Outcome 2: 144
Outcome 3: 171
Outcome 4: 153
Outcome 5: 178
Outcome 6: 177
