# Indexing and Slicing

## Example1: Given a 2D array of shape (6, 6), extract a 2x2 sub-array starting from the element at position (1, 1).


In [1]:
import numpy as np


array_2d = np.array([
    [ 0,  1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10, 11],
    [12, 13, 14, 15, 16, 17],
    [18, 19, 20, 21, 22, 23],
    [24, 25, 26, 27, 28, 29],
    [30, 31, 32, 33, 34, 35]
])

sub_array_method1 = array_2d[1:3, 1:3]

print("Method 1:")
print(sub_array_method1)


Method 1:
[[ 7  8]
 [13 14]]


In [2]:
sub_array_method2 = np.array([row[1:3] for row in array_2d[1:3]])

print("Method 2:")
print(sub_array_method2)


Method 2:
[[ 7  8]
 [13 14]]


In [3]:
sub_array_method3 = np.zeros((2, 2), dtype=array_2d.dtype)
for i in range(2):
    for j in range(2):
        sub_array_method3[i, j] = array_2d[i + 1, j + 1]

print("Method 3:")
print(sub_array_method3)


Method 3:
[[ 7  8]
 [13 14]]


In [4]:
sub_array_method4 = np.empty((2, 2), dtype=array_2d.dtype)
sub_array_method4[0, 0] = array_2d[1, 1]
sub_array_method4[0, 1] = array_2d[1, 2]
sub_array_method4[1, 0] = array_2d[2, 1]
sub_array_method4[1, 1] = array_2d[2, 2]

print("Method 4:")
print(sub_array_method4)


Method 4:
[[ 7  8]
 [13 14]]


In [5]:
rows = np.array([1, 2])
cols = np.array([1, 2])
sub_array_method5 = array_2d[rows[:, np.newaxis], cols]

print("Method 5:")
print(sub_array_method5)


Method 5:
[[ 7  8]
 [13 14]]


## Example2: From a 3D array of shape (3, 2, 1), extract all elements in the first two rows and all columns of the second slice along the third axis.


In [6]:
array_3d = np.array([
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
sub_array_method1 = array_3d[:2, :, 0]

print("Method 1:")
print(sub_array_method1)


Method 1:
[[1 2]
 [3 4]]


In [7]:
sub_array_method2 = np.array([array_3d[i, :, 0] for i in range(2)])

print("Method 2:")
print(sub_array_method2)


Method 2:
[[1 2]
 [3 4]]


In [8]:
indices = np.ix_([0, 1], np.arange(2), [0])
sub_array_method3 = array_3d[indices]

print("Method 3:")
print(sub_array_method3[:, :, 0])


Method 3:
[[1 2]
 [3 4]]


In [9]:
reshaped_array = array_3d.reshape(3, 2)  # reshape to (3, 2)
sub_array_method4 = reshaped_array[:2, :]

print("Method 4:")
print(sub_array_method4)


Method 4:
[[1 2]
 [3 4]]


In [10]:
transposed_array = np.transpose(array_3d, (0, 2, 1))  # transpose to (3, 1, 2)
sub_array_method5 = transposed_array[:2, 0, :]

print("Method 5:")
print(sub_array_method5)


Method 5:
[[1 2]
 [3 4]]


## Example3: Given an array of integers, use fancy indexing to extract elements at positions [1, 3, 4, 6].


In [11]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
extracted_method1 = arr[[1, 3, 4, 6]]
print("Method 1:")
print("Extracted elements:", extracted_method1)


Method 1:
Extracted elements: [20 40 50 70]


In [13]:
extracted_method2 = np.take(arr, [1, 3, 4, 6])

print("Method 2:")
print("Extracted elements:", extracted_method2)


Method 2:
Extracted elements: [20 40 50 70]


In [14]:
indices = np.array([False, True, False, True, True, False, True])
extracted_method3 = arr[indices]

print("Method 3:")
print("Extracted elements:", extracted_method3)


Method 3:
Extracted elements: [20 40 50 70]


In [15]:
indices = [1, 3, 4, 6]
extracted_method4 = arr[np.ix_(indices)]

print("Method 4:")
print("Extracted elements:", extracted_method4)


Method 4:
Extracted elements: [20 40 50 70]


In [16]:
mask = np.array([False, True, False, True, True, False, True])
extracted_method5 = np.compress(mask, arr)

print("Method 5:")
print("Extracted elements:", extracted_method5)


Method 5:
Extracted elements: [20 40 50 70]


## Example4: Given a 2D array, use fancy indexing to select rows [0, 2, 2] and columns [1, 3].


In [26]:
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
rows = [0, 2, 2]
cols = [1, 3]

result = array[rows, :][:, cols]
print(result)


[[ 2  4]
 [10 12]
 [10 12]]


In [27]:
result = array[np.ix_(rows, cols)]
print(result)

[[ 2  4]
 [10 12]
 [10 12]]


In [28]:
result = np.array([[array[row, col] for col in cols] for row in rows])
print(result)

[[ 2  4]
 [10 12]
 [10 12]]


In [29]:
rows = np.array([0, 2, 2])
cols = np.array([1, 3])

# Using meshgrid
row_indices, col_indices = np.meshgrid(rows, cols, indexing='ij')
result = array[row_indices, col_indices]
print(result)

[[ 2  4]
 [10 12]
 [10 12]]


In [34]:
ixgrid = np.ix_(rows, cols)

# Advanced indexing
result = array[ixgrid]
print(result)

[[ 2  4]
 [10 12]
 [10 12]]


## Example5: From a 1D array of random integers, extract all elements that are greater than 8.


In [35]:
array = np.random.randint(0, 20, size=15)

# Using boolean indexing
result = array[array > 8]
print("Original array:", array)
print("Elements greater than 8:", result)


Original array: [10 13 19  6  2  1 11 16  8  7  2 13 14 16 14]
Elements greater than 8: [10 13 19 11 16 13 14 16 14]


In [36]:
indices = np.where(array > 8)
result = array[indices]
print("Original array:", array)
print("Elements greater than 8:", result)

Original array: [10 13 19  6  2  1 11 16  8  7  2 13 14 16 14]
Elements greater than 8: [10 13 19 11 16 13 14 16 14]


In [37]:
result = np.array([x for x in array if x > 8])
print("Original array:", array)
print("Elements greater than 8:", result)

Original array: [10 13 19  6  2  1 11 16  8  7  2 13 14 16 14]
Elements greater than 8: [10 13 19 11 16 13 14 16 14]


In [38]:
result = np.extract(array > 8, array)
print("Original array:", array)
print("Elements greater than 8:", result)

Original array: [10 13 19  6  2  1 11 16  8  7  2 13 14 16 14]
Elements greater than 8: [10 13 19 11 16 13 14 16 14]


In [39]:
result = np.fromiter(filter(lambda x: x > 8, array), dtype=int)
print("Original array:", array)
print("Elements greater than 8:", result)

Original array: [10 13 19  6  2  1 11 16  8  7  2 13 14 16 14]
Elements greater than 8: [10 13 19 11 16 13 14 16 14]


## Example6: Given a 2D array of shape (6, 6), replace all elements greater than 13 with the value 0.

In [40]:
array = np.random.randint(0, 20, size=(6, 6))

# Using boolean indexing
array[array > 13] = 0
print("Modified array:\n", array)


Modified array:
 [[ 0  0  0  0  1  0]
 [ 9  0  0  0 12 12]
 [ 1 11  0 10  0  0]
 [ 0  8  8  0 11 13]
 [ 2 13  7  8  2  8]
 [ 0  0  6  0  6  0]]


In [41]:
array = np.where(array > 13, 0, array)
print("Modified array:\n", array)


Modified array:
 [[ 0  0  0  0  1  0]
 [ 9  0  0  0 12 12]
 [ 1 11  0 10  0  0]
 [ 0  8  8  0 11 13]
 [ 2 13  7  8  2  8]
 [ 0  0  6  0  6  0]]


In [43]:
for i in range(array.shape[0]):
    for j in range(array.shape[1]):
        if array[i, j] > 13:
            array[i, j] = 0
print("Modified array:\n", array)

Modified array:
 [[ 0  0  0  0  1  0]
 [ 9  0  0  0 12 12]
 [ 1 11  0 10  0  0]
 [ 0  8  8  0 11 13]
 [ 2 13  7  8  2  8]
 [ 0  0  6  0  6  0]]


In [44]:
def replace_if_greater_than_13(x):
    return x if x <= 13 else 0

vectorized_replace = np.vectorize(replace_if_greater_than_13)
array = vectorized_replace(array)
print("Modified array:\n", array)

Modified array:
 [[ 0  0  0  0  1  0]
 [ 9  0  0  0 12 12]
 [ 1 11  0 10  0  0]
 [ 0  8  8  0 11 13]
 [ 2 13  7  8  2  8]
 [ 0  0  6  0  6  0]]


In [45]:
np.putmask(array, array > 13, 0)
print("Modified array:\n", array)

Modified array:
 [[ 0  0  0  0  1  0]
 [ 9  0  0  0 12 12]
 [ 1 11  0 10  0  0]
 [ 0  8  8  0 11 13]
 [ 2 13  7  8  2  8]
 [ 0  0  6  0  6  0]]


# Bradcasting

## Example1: Add a 1D array of shape (3,) to each row of a 2D array of shape (4, 3).


In [46]:
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9],
                     [10, 11, 12]])

array_1d = np.array([1, 2, 3])

result = array_2d + array_1d[np.newaxis, :]
print("Method 1:\n", result)


Method 1:
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


In [48]:
result = array_2d + np.expand_dims(array_1d, axis=0)
print("Method 2:\n", result)


Method 2:
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


In [49]:
result = array_2d + array_1d
print("Method 3:\n", result)


Method 3:
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


In [50]:
result = array_2d + np.tile(array_1d, (array_2d.shape[0], 1))
print("Method 4:\n", result)


Method 4:
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


In [51]:
result = array_2d + np.broadcast_to(array_1d, (array_2d.shape[0], array_2d.shape[1]))
print("Method 5:\n", result)


Method 5:
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


## Example2: Multiply a 2D array of shape (3, 3) by a 1D array of shape (3,)

In [59]:
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

array_1d = np.array([1, 2, 3])

result = array_2d * array_1d[:, np.newaxis]
print("Method 1:\n", result)


Method 1:
 [[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]


In [60]:
result = array_2d * np.expand_dims(array_1d, axis=1)
print("Method 2:\n", result)


Method 2:
 [[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]


In [61]:
result = array_2d * array_1d.reshape(-1, 1)
print("Method 3:\n", result)


Method 3:
 [[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]


In [64]:
result = array_2d * np.broadcast_to(array_1d, (3, 3))
print("Method 4:\n", result)


Method 4:
 [[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


In [65]:
result = array_2d * np.expand_dims(array_1d, axis=1)
print("Method 3:\n", result)


Method 3:
 [[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]


## Example3: Create two 2D arrays of shapes (3, 1) and (1, 4) respectively, and perform element-wise addition.
`

In [66]:
array1 = np.array([[1],
                   [2],
                   [3]])

array2 = np.array([[1, 2, 3, 4]])

result = array1 + array2
print("Method 1:\n", result)

Method 1:
 [[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


In [67]:
result = array1 + array2[np.newaxis, :]
print("Method 2:\n", result)


Method 2:
 [[[2 3 4 5]
  [3 4 5 6]
  [4 5 6 7]]]


In [68]:
result = array1 + array2.reshape(1, -1)
print("Method 3:\n", result)


Method 3:
 [[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


In [69]:
result = array1 + np.expand_dims(array2, axis=0)
print("Method 4:\n", result)


Method 4:
 [[[2 3 4 5]
  [3 4 5 6]
  [4 5 6 7]]]


In [70]:
result = array1 + np.broadcast_to(array2, (3, 4))
print("Method 5:\n", result)


Method 5:
 [[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


## Example4: Given a 3D array of shape (2, 3, 4), add a 2D array of shape (3, 4) to each 2D slice along the first axis.


In [71]:
array_3d = np.array([[[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]],
                     
                     [[13, 14, 15, 16],
                      [17, 18, 19, 20],
                      [21, 22, 23, 24]]])


array_2d = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

result = array_3d + array_2d[np.newaxis, :, :]
print("Method 1:\n", result)


Method 1:
 [[[ 2  4  6  8]
  [10 12 14 16]
  [18 20 22 24]]

 [[14 16 18 20]
  [22 24 26 28]
  [30 32 34 36]]]


In [72]:
result = array_3d + array_2d[np.newaxis]
print("Method 2:\n", result)


Method 2:
 [[[ 2  4  6  8]
  [10 12 14 16]
  [18 20 22 24]]

 [[14 16 18 20]
  [22 24 26 28]
  [30 32 34 36]]]


In [73]:
result = array_3d + array_2d.reshape(1, 3, 4)
print("Method 3:\n", result)


Method 3:
 [[[ 2  4  6  8]
  [10 12 14 16]
  [18 20 22 24]]

 [[14 16 18 20]
  [22 24 26 28]
  [30 32 34 36]]]


In [74]:
result = array_3d + np.expand_dims(array_2d, axis=0)
print("Method 4:\n", result)


Method 4:
 [[[ 2  4  6  8]
  [10 12 14 16]
  [18 20 22 24]]

 [[14 16 18 20]
  [22 24 26 28]
  [30 32 34 36]]]


In [75]:
result = array_3d + np.tile(array_2d, (2, 1, 1))
print("Method 5:\n", result)


Method 5:
 [[[ 2  4  6  8]
  [10 12 14 16]
  [18 20 22 24]]

 [[14 16 18 20]
  [22 24 26 28]
  [30 32 34 36]]]


# More Examples

## Example1: Given a 2D array, use slicing to extract every second row and every second column, then add a 1D array to each row of the sliced array.


In [76]:
array_2d = np.array([[1, 2, 3, 4, 5],
                     [6, 7, 8, 9, 10],
                     [11, 12, 13, 14, 15],
                     [16, 17, 18, 19, 20]])


sliced_array = array_2d[::2, ::2]


array_to_add = np.array([1, 2])

result = sliced_array + array_to_add[:, np.newaxis]
print("Method 1:\n", result)

Method 1:
 [[ 2  4  6]
 [13 15 17]]


In [77]:
result = sliced_array + array_to_add.reshape(-1, 1)
print("Method 2:\n", result)


Method 2:
 [[ 2  4  6]
 [13 15 17]]


In [84]:
result = sliced_array + np.expand_dims(array_to_add, axis=1)
print("Method 3:\n", result)


Method 3:
 [[ 2  4  6]
 [13 15 17]]


In [85]:
sliced_array = array_2d[::2, ::2]
array_to_add = np.array([1, 2])
result = sliced_array + np.repeat(array_to_add[:, np.newaxis], sliced_array.shape[1], axis=1)
print("Method 4:\n", result)

Method 4:
 [[ 2  4  6]
 [13 15 17]]


In [86]:
result = sliced_array + np.broadcast_to(array_to_add[:, np.newaxis], sliced_array.shape)
print("Method 5:\n", result)


Method 5:
 [[ 2  4  6]
 [13 15 17]]


## Example2: From a 3D array of shape (3, 2, 1), extract a sub-array using slicing and then use broadcasting to subtract a 2D array from each slice along the third axis.


In [87]:
array_3d = np.array([[[1],
                      [2]],
                     
                     [[3],
                      [4]],
                     
                     [[5],
                      [6]]])


sub_array = array_3d[:, :, 0]


array_to_subtract = np.array([[1, 1],
                              [2, 2],
                              [3, 3]])

result = sub_array - array_to_subtract
print("Method 1:\n", result)


Method 1:
 [[0 1]
 [1 2]
 [2 3]]


In [88]:
result = sub_array - array_to_subtract.reshape(3, 2)
print("Method 2:\n", result)


Method 2:
 [[0 1]
 [1 2]
 [2 3]]


In [89]:
result = sub_array - np.expand_dims(array_to_subtract, axis=1)
print("Method 3:\n", result)


Method 3:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[-1  0]
  [ 1  2]
  [ 3  4]]

 [[-2 -1]
  [ 0  1]
  [ 2  3]]]


In [94]:
sub_array = array_3d[:, :, 0]


array_to_subtract = np.array([[1, 1],
                              [2, 2],
                              [3, 3]])

result = sub_array - np.tile(array_to_subtract, (1, 1))
print("Method 4:\n", result)

Method 4:
 [[0 1]
 [1 2]
 [2 3]]


In [95]:
result = np.zeros_like(sub_array)
for i in range(sub_array.shape[0]):
    result[i] = sub_array[i] - array_to_subtract[i]
print("Method 5:\n", result)


Method 5:
 [[0 1]
 [1 2]
 [2 3]]


## Example3: Given a 2D array, extract the diagonal elements and create a 1D array.

In [97]:
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

diagonal1 = np.diag(array_2d)
print("Method 1:", diagonal1)


Method 1: [1 5 9]


In [99]:
diagonal2 = array_2d[np.arange(array_2d.shape[0]), np.arange(array_2d.shape[0])]
print("Method 2:", diagonal2)


Method 2: [1 5 9]


In [100]:
diagonal3 = [array_2d[i, i] for i in range(array_2d.shape[0])]
print("Method 3:", np.array(diagonal3))


Method 3: [1 5 9]


In [101]:
diagonal4 = np.diagonal(array_2d, offset=0)
print("Method 4:", diagonal4)


Method 4: [1 5 9]


In [103]:
diagonal5 = [array_2d[i, i] for i in range(min(array_2d.shape))]
print("Method 5:", np.array(diagonal5))

Method 5: [1 5 9]


## Example4: Use slicing to reverse the order of elements in each row of a 2D array.

In [104]:
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])


reversed_array1 = array_2d[:, ::-1]
print("Method 1:\n", reversed_array1)


Method 1:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [105]:
reversed_array2 = np.flip(array_2d, axis=1)
print("Method 2:\n", reversed_array2)


Method 2:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [106]:
reversed_array3 = np.array([row[::-1] for row in array_2d])
print("Method 3:\n", reversed_array3)


Method 3:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [107]:
reversed_array4 = np.fliplr(array_2d)
print("Method 4:\n", reversed_array4)


Method 4:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [108]:
reversed_array5 = np.array([row[::-1] for row in array_2d])
print("Method 5:\n", reversed_array5)


Method 5:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


## Example5: Given a 3D array of shape (7, 6, 5), use slicing to extract a sub-array of shape (2, 3, 4) and then use broadcasting to add a 1D array of shape (4,) to each row along the third axis.


In [114]:
array_3d = np.random.randint(1, 10, size=(7, 6, 5))


sub_array = array_3d[:2, :3, :4]

array_to_add = np.array([1, 2, 3, 4])

result1 = sub_array + array_to_add
print("Method 1:\n", result1)


Method 1:
 [[[ 6  9 10  9]
  [ 3  3 10  7]
  [ 5  6  5  6]]

 [[ 8  8 10  6]
  [ 5 10  7 11]
  [10  5  4  6]]]


In [115]:
result2 = sub_array + array_to_add.reshape(1, 1, -1)
print("Method 2:\n", result2)


Method 2:
 [[[ 6  9 10  9]
  [ 3  3 10  7]
  [ 5  6  5  6]]

 [[ 8  8 10  6]
  [ 5 10  7 11]
  [10  5  4  6]]]


In [116]:
result3 = sub_array + np.expand_dims(array_to_add, axis=(0, 1))
print("Method 3:\n", result3)


Method 3:
 [[[ 6  9 10  9]
  [ 3  3 10  7]
  [ 5  6  5  6]]

 [[ 8  8 10  6]
  [ 5 10  7 11]
  [10  5  4  6]]]


In [117]:
result4 = sub_array + np.tile(array_to_add, (2, 3, 1))
print("Method 4:\n", result4)


Method 4:
 [[[ 6  9 10  9]
  [ 3  3 10  7]
  [ 5  6  5  6]]

 [[ 8  8 10  6]
  [ 5 10  7 11]
  [10  5  4  6]]]


In [118]:
result5 = sub_array + np.broadcast_to(array_to_add, sub_array.shape)
print("Method 5:\n", result5)


Method 5:
 [[[ 6  9 10  9]
  [ 3  3 10  7]
  [ 5  6  5  6]]

 [[ 8  8 10  6]
  [ 5 10  7 11]
  [10  5  4  6]]]


## Example6: Create a 2D array and use both slicing and broadcasting to set the last column to the sum of the first two columns for each row.


In [120]:
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

array_2d[:, -1] = array_2d[:, 0] + array_2d[:, 1]
print("Method 1:\n", array_2d)


Method 1:
 [[ 1  2  3]
 [ 4  5  9]
 [ 7  8 15]]


In [121]:
array_2d[:, -1] = np.sum(array_2d[:, :2], axis=1)
print("Method 2:\n", array_2d)


Method 2:
 [[ 1  2  3]
 [ 4  5  9]
 [ 7  8 15]]


In [122]:
array_2d[:, -1] = np.add(array_2d[:, 0], array_2d[:, 1])
print("Method 3:\n", array_2d)


Method 3:
 [[ 1  2  3]
 [ 4  5  9]
 [ 7  8 15]]


In [123]:
array_2d[:, -1] = np.apply_along_axis(lambda x: np.sum(x[:2]), axis=1, arr=array_2d)
print("Method 4:\n", array_2d)


Method 4:
 [[ 1  2  3]
 [ 4  5  9]
 [ 7  8 15]]


In [124]:
for row in array_2d:
    row[-1] = row[0] + row[1]
print("Method 5:\n", array_2d)


Method 5:
 [[ 1  2  3]
 [ 4  5  9]
 [ 7  8 15]]


# Advance Numpy

In [126]:
# Example1: # Creating a memory-mapped array

In [131]:
filename = 'memmapfile.dat'
memmap_arr = np.memmap(filename, dtype='float32', mode='w+', shape=(1000, 1000))
memmap_arr[:] = np.random.rand(1000, 1000)
del memmap_arr
memmap_arr_read = np.memmap(filename, dtype='float32', mode='r', shape=(1000, 1000))
print("First few elements of the memory-mapped array:")
print(memmap_arr_read[:3, :3])  
del memmap_arr_read



First few elements of the memory-mapped array:
[[0.9672966  0.0524439  0.41666952]
 [0.4265525  0.4346608  0.54756117]
 [0.60372233 0.6655536  0.7279106 ]]


In [132]:
# Example2: Structured Arrays and Advanced Indexing

In [134]:
data = np.array([(1, 2.0, 'Hello'),
                 (2, 3.5, 'World')],
                dtype=[('id', int), ('value', float), ('message', 'U10')])


print("Structured Array:")
print(data)
print()


print("Accessing elements by column names:")
print("ID:", data['id'])
print("Values:", data['value'])
print("Messages:", data['message'])
print()


print("Boolean indexing based on conditions:")
print("Values greater than 2:")
print(data[data['value'] > 2])
print()


print("Creating a new structured array from selected columns:")
new_data = np.array(data[['id', 'message']])
print(new_data)


Structured Array:
[(1, 2. , 'Hello') (2, 3.5, 'World')]

Accessing elements by column names:
ID: [1 2]
Values: [2.  3.5]
Messages: ['Hello' 'World']

Boolean indexing based on conditions:
Values greater than 2:
[(2, 3.5, 'World')]

Creating a new structured array from selected columns:
[(1, 'Hello') (2, 'World')]


In [135]:
## Example3:  Vectorization, and Masking

In [140]:
arr = np.random.randint(1, 20, size=(5, 5))
print("Original Array:")
print(arr)
print()


squared_arr = np.square(arr)
print("Squared Array (Element-wise operation):")
print(squared_arr)
print()

mask = arr > 10
print("Mask (Elements > 10):")
print(mask)
print()
masked_arr = arr[mask]
print("Masked Array (Elements > 10):")
print(masked_arr)
print()

squared_masked_arr = np.square(arr[mask])
print("Squared Masked Array (Squared elements > 10):")
print(squared_masked_arr)


Original Array:
[[14  9 18  7 19]
 [14  3 11  2  6]
 [16  9 14 12 14]
 [ 8  4  3 16 19]
 [17 19  3 13  1]]

Squared Array (Element-wise operation):
[[196  81 324  49 361]
 [196   9 121   4  36]
 [256  81 196 144 196]
 [ 64  16   9 256 361]
 [289 361   9 169   1]]

Mask (Elements > 10):
[[ True False  True False  True]
 [ True False  True False False]
 [ True False  True  True  True]
 [False False False  True  True]
 [ True  True False  True False]]

Masked Array (Elements > 10):
[14 18 19 14 11 16 14 12 14 16 19 17 19 13]

Squared Masked Array (Squared elements > 10):
[196 324 361 196 121 256 196 144 196 256 361 289 361 169]
